services:
  ts3-server-hub:
    container_name: ts3-server-hub
    image: ghcr.io/linmo-33/ts3-server-web:latest
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
